GET http://localhost:3000/words

###

GET http://localhost:3000/words/634448c1dab1fe117ca64313

###

POST http://localhost:3000/words
Content-Type: application/json

{
  "luganda": "Kale",
  "english": "Okay"
}

